'use client';
import { FormEvent,useEffect,useState } from 'react';import { api,errorMessage } from '@/lib/api';import { Company,Paginated } from '@/lib/types';import Modal from '@/components/Modal';import Pagination from '@/components/Pagination';import PageHeader from '@/components/PageHeader';
const blank={name:'',industry:'',website:'',phone:'',email:'',address:''};
export default function Companies(){const[data,setData]=useState<Paginated<Company>>({data:[],total:0,page:1,limit:10});const[page,setPage]=useState(1);const[search,setSearch]=useState('');const[order,setOrder]=useState<'ASC'|'DESC'>('DESC');const[open,setOpen]=useState(false);const[editing,setEditing]=useState<Company|null>(null);const[form,setForm]=useState(blank);const[error,setError]=useState('');
 const load=()=>api.get('/companies',{params:{page,limit:10,search,order}}).then(r=>setData(r.data));useEffect(()=>{load()},[page,search,order]);
 const start=(c?:Company)=>{setEditing(c||null);setForm(c?{name:c.name,industry:c.industry||'',website:c.website||'',phone:c.phone||'',email:c.email||'',address:c.address||''}:blank);setOpen(true);setError('')};
 async function submit(e:FormEvent){e.preventDefault();try{const payload={...form,email:form.email||undefined};editing?await api.patch(`/companies/${editing.id}`,payload):await api.post('/companies',payload);setOpen(false);load();}catch(err){setError(errorMessage(err))}}
 async function remove(id:string){if(confirm('Delete this company?')){await api.delete(`/companies/${id}`);load();}}
 return <><PageHeader title="Companies" description="Manage businesses and organizations in your CRM." action={<button className="btn-primary" onClick={()=>start()}>+ Add Company</button>}/><div className="mb-4 flex flex-wrap gap-3"><input className="input max-w-md" placeholder="Search company or industry..." value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}}/><select className="input max-w-44" value={order} onChange={e=>setOrder(e.target.value as 'ASC'|'DESC')}><option value="DESC">Newest first</option><option value="ASC">Oldest first</option></select></div><div className="table-wrap"><table className="table"><thead><tr><th>Name</th><th>Industry</th><th>Contact</th><th>Website</th><th>Actions</th></tr></thead><tbody>{data.data.map(c=><tr key={c.id}><td className="font-semibold">{c.name}</td><td>{c.industry||'-'}</td><td>{c.email||c.phone||'-'}</td><td>{c.website||'-'}</td><td><div className="flex gap-2"><button className="btn-secondary" onClick={()=>start(c)}>Edit</button><button className="btn-danger" onClick={()=>remove(c.id)}>Delete</button></div></td></tr>)}</tbody></table></div><Pagination page={page} total={data.total} limit={10} onChange={setPage}/><Modal open={open} title={editing?'Edit Company':'Add Company'} onClose={()=>setOpen(false)}>{error&&<p className="mb-3 text-sm text-red-600">{error}</p>}<form className="grid gap-4 md:grid-cols-2" onSubmit={submit}>{Object.entries(form).map(([key,value])=><div key={key} className={key==='address'?'md:col-span-2':''}><label className="label capitalize">{key}</label>{key==='address'?<textarea className="input" value={value} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input className="input" value={value} required={key==='name'} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</div>)}<div className="md:col-span-2 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn-primary">Save Company</button></div></form></Modal></>}
