'use client';
import { FormEvent,useEffect,useState } from 'react';import { api,errorMessage } from '@/lib/api';import { Company,Contact,Paginated } from '@/lib/types';import Modal from '@/components/Modal';import Pagination from '@/components/Pagination';import PageHeader from '@/components/PageHeader';
const blank={firstName:'',lastName:'',email:'',phone:'',position:'',companyId:''};
export default function Contacts(){const[data,setData]=useState<Paginated<Contact>>({data:[],total:0,page:1,limit:10});const[companies,setCompanies]=useState<Company[]>([]);const[page,setPage]=useState(1);const[search,setSearch]=useState('');const[order,setOrder]=useState<'ASC'|'DESC'>('DESC');const[open,setOpen]=useState(false);const[editing,setEditing]=useState<Contact|null>(null);const[form,setForm]=useState(blank);const[error,setError]=useState('');
 const load=()=>api.get('/contacts',{params:{page,limit:10,search,order}}).then(r=>setData(r.data));useEffect(()=>{load()},[page,search,order]);useEffect(()=>{api.get('/companies',{params:{limit:100}}).then(r=>setCompanies(r.data.data))},[]);
 const start=(c?:Contact)=>{setEditing(c||null);setForm(c?{firstName:c.firstName,lastName:c.lastName,email:c.email||'',phone:c.phone||'',position:c.position||'',companyId:c.company?.id||''}:blank);setOpen(true);setError('')};
 async function submit(e:FormEvent){e.preventDefault();try{const payload={...form,email:form.email||undefined,companyId:form.companyId||undefined};editing?await api.patch(`/contacts/${editing.id}`,payload):await api.post('/contacts',payload);setOpen(false);load();}catch(err){setError(errorMessage(err))}}
 async function remove(id:string){if(confirm('Delete this contact?')){await api.delete(`/contacts/${id}`);load();}}
 return <><PageHeader title="Contacts" description="Store people and connect them to companies." action={<button className="btn-primary" onClick={()=>start()}>+ Add Contact</button>}/><div className="mb-4 flex flex-wrap gap-3"><input className="input max-w-md" placeholder="Search name or email..." value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}}/><select className="input max-w-44" value={order} onChange={e=>setOrder(e.target.value as 'ASC'|'DESC')}><option value="DESC">Newest first</option><option value="ASC">Oldest first</option></select></div><div className="table-wrap"><table className="table"><thead><tr><th>Name</th><th>Company</th><th>Email</th><th>Phone</th><th>Position</th><th>Actions</th></tr></thead><tbody>{data.data.map(c=><tr key={c.id}><td className="font-semibold">{c.firstName} {c.lastName}</td><td>{c.company?.name||'-'}</td><td>{c.email||'-'}</td><td>{c.phone||'-'}</td><td>{c.position||'-'}</td><td><div className="flex gap-2"><button className="btn-secondary" onClick={()=>start(c)}>Edit</button><button className="btn-danger" onClick={()=>remove(c.id)}>Delete</button></div></td></tr>)}</tbody></table></div><Pagination page={page} total={data.total} limit={10} onChange={setPage}/><Modal open={open} title={editing?'Edit Contact':'Add Contact'} onClose={()=>setOpen(false)}>{error&&<p className="text-red-600">{error}</p>}<form className="grid gap-4 md:grid-cols-2" onSubmit={submit}><div><label className="label">First Name</label><input className="input" required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></div><div><label className="label">Last Name</label><input className="input" required value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></div><div><label className="label">Email</label><input className="input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><label className="label">Phone</label><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><label className="label">Position</label><input className="input" value={form.position} onChange={e=>setForm({...form,position:e.target.value})}/></div><div><label className="label">Company</label><select className="input" value={form.companyId} onChange={e=>setForm({...form,companyId:e.target.value})}><option value="">No company</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="md:col-span-2 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn-primary">Save Contact</button></div></form></Modal></>}
